/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author Pablo
 */
public class calculadora extends javax.swing.JFrame {
//declaracion de variables
    private Boolean igual, inicio = true, ejercicio1=true, ejercicio2=true; 
    private double a, b, c, memoria = 0, resultado, valor1, valor2,res;
    private String cadena, funciones, tipo_ejercicio;

    /**
     * Creates new form calculadora
     */
    public calculadora() { //metodo constructor
        initComponents();
        setLocationRelativeTo(null); //Hace que la calculadora se muestre en el centro de la pantalla

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_7 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_division = new javax.swing.JButton();
        btn_mutiplica = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_borrar = new javax.swing.JButton();
        btn_CE = new javax.swing.JButton();
        btn_C = new javax.swing.JButton();
        btn_mas_menos = new javax.swing.JButton();
        btn_MC = new javax.swing.JButton();
        btn_MR = new javax.swing.JButton();
        btn_MS = new javax.swing.JButton();
        btn_M_mas = new javax.swing.JButton();
        mtn_M_menos = new javax.swing.JButton();
        btn_porciento = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        pantalla_abajo = new javax.swing.JTextField();
        pantalla_arriba = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        btn_7.setBackground(new java.awt.Color(153, 153, 153));
        btn_7.setText("7");
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });

        btn_8.setBackground(new java.awt.Color(153, 153, 153));
        btn_8.setText("8");
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });

        btn_9.setBackground(new java.awt.Color(153, 153, 153));
        btn_9.setText("9");
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });

        btn_4.setBackground(new java.awt.Color(153, 153, 153));
        btn_4.setText("4");
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });

        btn_5.setBackground(new java.awt.Color(153, 153, 153));
        btn_5.setText("5");
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });

        btn_6.setBackground(new java.awt.Color(153, 153, 153));
        btn_6.setText("6");
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });

        btn_1.setBackground(new java.awt.Color(153, 153, 153));
        btn_1.setText("1");
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });

        btn_2.setBackground(new java.awt.Color(153, 153, 153));
        btn_2.setText("2");
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });

        btn_3.setBackground(new java.awt.Color(153, 153, 153));
        btn_3.setText("3");
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });

        btn_0.setBackground(new java.awt.Color(153, 153, 153));
        btn_0.setText("0");
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });

        btn_punto.setBackground(new java.awt.Color(153, 153, 153));
        btn_punto.setText(".");
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });

        btn_division.setBackground(new java.awt.Color(153, 153, 153));
        btn_division.setText("/");
        btn_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_divisionActionPerformed(evt);
            }
        });

        btn_mutiplica.setBackground(new java.awt.Color(153, 153, 153));
        btn_mutiplica.setText("*");
        btn_mutiplica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mutiplicaActionPerformed(evt);
            }
        });

        btn_resta.setBackground(new java.awt.Color(153, 153, 153));
        btn_resta.setText("-");
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });

        btn_suma.setBackground(new java.awt.Color(153, 153, 153));
        btn_suma.setText("+");
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });

        btn_igual.setBackground(new java.awt.Color(153, 153, 153));
        btn_igual.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btn_igual.setText("=");
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setFont(new java.awt.Font("Dialog", 0, 8)); // NOI18N
        jButton2.setText("MOD");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btn_borrar.setBackground(new java.awt.Color(153, 153, 153));
        btn_borrar.setText("<--");
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });

        btn_CE.setBackground(new java.awt.Color(153, 153, 153));
        btn_CE.setText("CE");
        btn_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CEActionPerformed(evt);
            }
        });

        btn_C.setBackground(new java.awt.Color(153, 153, 153));
        btn_C.setText("C");
        btn_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CActionPerformed(evt);
            }
        });

        btn_mas_menos.setBackground(new java.awt.Color(153, 153, 153));
        btn_mas_menos.setText("±");
        btn_mas_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mas_menosActionPerformed(evt);
            }
        });

        btn_MC.setBackground(new java.awt.Color(153, 153, 153));
        btn_MC.setText("MC");
        btn_MC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MCActionPerformed(evt);
            }
        });

        btn_MR.setBackground(new java.awt.Color(153, 153, 153));
        btn_MR.setText("MR");
        btn_MR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MRActionPerformed(evt);
            }
        });

        btn_MS.setBackground(new java.awt.Color(153, 153, 153));
        btn_MS.setText("MS");
        btn_MS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MSActionPerformed(evt);
            }
        });

        btn_M_mas.setBackground(new java.awt.Color(153, 153, 153));
        btn_M_mas.setText("M+");
        btn_M_mas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_M_masActionPerformed(evt);
            }
        });

        mtn_M_menos.setBackground(new java.awt.Color(153, 153, 153));
        mtn_M_menos.setText("M-");
        mtn_M_menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtn_M_menosActionPerformed(evt);
            }
        });

        btn_porciento.setBackground(new java.awt.Color(153, 153, 153));
        btn_porciento.setText("%");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pantalla_abajo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla_abajo.setText("0");
        pantalla_abajo.setBorder(null);
        pantalla_abajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pantalla_abajoActionPerformed(evt);
            }
        });

        pantalla_arriba.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pantalla_arriba.setBorder(null);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pantalla_arriba)
                    .addComponent(pantalla_abajo))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pantalla_arriba, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pantalla_abajo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mutiplica, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_MC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_CE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_MR, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_MS, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btn_mas_menos, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_M_mas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mtn_M_menos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_porciento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_MC)
                    .addComponent(btn_MR)
                    .addComponent(btn_MS)
                    .addComponent(btn_M_mas)
                    .addComponent(mtn_M_menos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_CE)
                        .addComponent(btn_C)
                        .addComponent(btn_mas_menos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_porciento, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_division, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_mutiplica, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_resta, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_punto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_suma, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_igual, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//boton numerico
    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        if (inicio == true) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("0");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "0");
        }
    }//GEN-LAST:event_btn_0ActionPerformed
//boton numerico
    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        if (inicio == true) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("1");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "1");
        }
    }//GEN-LAST:event_btn_1ActionPerformed
//boton numerico
    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        if (inicio == true) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("5");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "5");
        }
    }//GEN-LAST:event_btn_5ActionPerformed
//boton resta
    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        igual = true;
        inicio = true;
        //condicion para la operacion resta 
        if (ejercicio1 = true) {
            valor1 = Double.parseDouble(pantalla_abajo.getText());
              res=valor1;
            double backupValue = (Double) valor1;
            pantalla_arriba.setText(" ");
            pantalla_arriba.setText(backupValue + " " + "-" + " ");
            ejercicio1 = false;
        } else {
            if (ejercicio2 = true) {
                valor2 = Double.parseDouble(pantalla_abajo.getText());
                pantalla_arriba.setText(" ");
                pantalla_arriba.setText(pantalla_arriba.getText() + "-");
                ejercicio2 = false;
            } else {
                pantalla_abajo.setText(pantalla_abajo.getText() + "-");
                operaciones(resultado, valor2);
            }

        }
    }//GEN-LAST:event_btn_restaActionPerformed
//boton MC
    private void btn_MCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MCActionPerformed
        memoria = 0;       
    }//GEN-LAST:event_btn_MCActionPerformed
//pantalla de abajo
    private void pantalla_abajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pantalla_abajoActionPerformed
        if ("0".equals(pantalla_abajo.getText())) {
            pantalla_abajo.setText("");

        }
    }//GEN-LAST:event_pantalla_abajoActionPerformed
//boton numerico
    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        if (inicio == true) {//if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("2");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "2");
        }
    }//GEN-LAST:event_btn_2ActionPerformed
//boton numerico
    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        if (inicio == true) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("3");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "3");
        }
    }//GEN-LAST:event_btn_3ActionPerformed
//boton numerico
    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        if (inicio == true) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("4");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "4");
        }
    }//GEN-LAST:event_btn_4ActionPerformed
//boton numerico
    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        if (inicio == true) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("6");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "6");
        }
    }//GEN-LAST:event_btn_6ActionPerformed
//boton numerico
    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        if (inicio == true) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("7");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "7");
        }
    }//GEN-LAST:event_btn_7ActionPerformed
//boton numerico
    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        if (inicio == true) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("8");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "8");
        }
    }//GEN-LAST:event_btn_8ActionPerformed
//boton numerico
    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        if (inicio == true) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
            pantalla_abajo.setText(" ");
            pantalla_abajo.setText("9");
            inicio = false;
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + "9");
        }
    }//GEN-LAST:event_btn_9ActionPerformed
//boton punto
    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        if (pantalla_abajo.getText().contains(".")) { //if para que al presionar el boton se muestre en la pantalla con su respectivo valor
        } else {
            pantalla_abajo.setText(pantalla_abajo.getText() + ".");
            inicio = false;
        }
    }//GEN-LAST:event_btn_puntoActionPerformed
//case donde se encuentra cada una de las operaciones
     private void operaciones(double valor1, double valor2) {
        switch (tipo_ejercicio) {
            //case duncion suma
            case "+":
                resultado = valor1 + valor2;
                pantalla_abajo.setText(resultado + "");
                res = resultado; //poner esto al final de todos los case
                break;
            //case funcion resta
            case "-":
                resultado = valor1 - valor2;
                pantalla_abajo.setText(resultado + "");
                valor1 = Double.parseDouble(pantalla_abajo.getText());
                res = resultado;
                break;
            //case funcion multiplicacion
            case "*":
                resultado = valor1 * valor2;
                pantalla_abajo.setText(resultado + "");
                valor1 = Double.parseDouble(pantalla_abajo.getText());
                res = resultado;
                break;
            //case funcion division
            case "/":
                if (valor2 == 0) {
                    pantalla_abajo.setText("no divisible entre 0");
                    break;
                } else {
                    resultado = valor1 / valor2;
                    pantalla_abajo.setText(resultado + "");
                    valor1 = Double.parseDouble(pantalla_abajo.getText());
                    res = resultado;
                    break;
                }
        }

    }
//boton suma
    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        igual = true;
        inicio = true;
        //condicion para la operacion suma
        if (ejercicio1 == true) {
            valor1 = Double.parseDouble(pantalla_abajo.getText());
            res=valor1;
            double backupValue = (Double) valor1;
            pantalla_arriba.setText(pantalla_arriba.getText() + " " +valor1+ "+" + " ");
            ejercicio1 = false;
            tipo_ejercicio="+";
        } else {
            if (ejercicio2 == true) {
                valor2 = Double.parseDouble(pantalla_abajo.getText());
                pantalla_arriba.setText(pantalla_arriba.getText()+valor2+  "+");
                operaciones(res, valor2);
            } else {
                pantalla_abajo.setText(pantalla_abajo.getText() + "+");
                operaciones(resultado, valor2);

            }
        }
    }//GEN-LAST:event_btn_sumaActionPerformed
//boton multiplicacion
    private void btn_mutiplicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mutiplicaActionPerformed
        igual = true;
        inicio = true;
        //condicion para la operacion multiplicación   
        if (ejercicio1 = true) {
            valor1 = Double.parseDouble(pantalla_abajo.getText());
              res=valor1;
            double backupValue = (Double) valor1;
            //pantalla_arriba.setText(" ");
            pantalla_arriba.setText(pantalla_arriba.getText() +backupValue+ " " + "*" + " ");
            ejercicio1 = false;
        } else {
            if (ejercicio2 = true) {
                valor2 = Double.parseDouble(pantalla_abajo.getText());
                //pantalla_arriba.setText(" ");
                pantalla_arriba.setText(pantalla_arriba.getText() + "*");
                ejercicio2 = false;
            } else {
                pantalla_abajo.setText(pantalla_abajo.getText() + "*");
                operaciones(resultado, valor2);
            }

        }
    }//GEN-LAST:event_btn_mutiplicaActionPerformed
//boton division
    private void btn_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_divisionActionPerformed
        igual = true;
        inicio = true;
        //condicion para la operacion división   
        if (ejercicio1 = true) {
            valor1 = Double.parseDouble(pantalla_abajo.getText());
              res=valor1;
            double backupValue = (Double) valor1;
            pantalla_arriba.setText(" ");
            pantalla_arriba.setText(backupValue + " " + "/" + " ");
            ejercicio1 = false;
        } else {
            if (ejercicio2 = true) {
                valor2 = Double.parseDouble(pantalla_abajo.getText());
                pantalla_arriba.setText(" ");
                pantalla_arriba.setText(pantalla_arriba.getText() + "/");
                ejercicio2 = false;
            } else {
                pantalla_abajo.setText(pantalla_abajo.getText() + "/");
                operaciones(resultado, valor2);
            }

        }
        tipo_ejercicio= "/";
    }//GEN-LAST:event_btn_divisionActionPerformed
//boton igual
    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        inicio = true;
        ejercicio1 = true;
        if (igual = true) {
            if (tipo_ejercicio == null) {

            } else {
                valor2 = Double.parseDouble(pantalla_abajo.getText());
                pantalla_arriba.setText(" ");
                operaciones(valor1, valor2);
                igual = false;
            }
        } else {
            pantalla_arriba.setText(" ");
            operaciones(valor1, valor2);
        }
    }//GEN-LAST:event_btn_igualActionPerformed
//boton para borrar
    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
        if (inicio = true) {
            pantalla_abajo.setText("0");
        } else {
            pantalla_abajo.setText("");
            
        }
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CEActionPerformed
        if (pantalla_abajo.getText().length() > 1) {
            pantalla_abajo.setText(pantalla_abajo.getText().substring(0, pantalla_abajo.getText().length() -1));
            if (pantalla_abajo.getText().length()== 1) {
                pantalla_abajo.setText("0");
                inicio = true;
            }
        }
    }//GEN-LAST:event_btn_CEActionPerformed

    private void btn_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CActionPerformed
        pantalla_abajo.setText("0");
        pantalla_arriba.setText("");
        inicio = true;
        ejercicio1 = true;
        ejercicio2 = true;
        igual = true;
        valor1 = 0;
        valor2 = 0;
        resultado = 0;
    }//GEN-LAST:event_btn_CActionPerformed

    private void btn_MRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MRActionPerformed
        pantalla_abajo.setText(memoria + " ");
    }//GEN-LAST:event_btn_MRActionPerformed

    private void btn_MSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MSActionPerformed
        memoria = Double.parseDouble(pantalla_abajo.getText());
    }//GEN-LAST:event_btn_MSActionPerformed

    private void btn_M_masActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_M_masActionPerformed
        memoria = memoria+Double.parseDouble(pantalla_abajo.getText());
    }//GEN-LAST:event_btn_M_masActionPerformed

    private void mtn_M_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtn_M_menosActionPerformed
        memoria = memoria - Double.parseDouble(pantalla_abajo.getText());
    }//GEN-LAST:event_mtn_M_menosActionPerformed

    private void btn_mas_menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mas_menosActionPerformed
        double num1 = 0, num2, num3;
        num2 = Double.parseDouble(pantalla_abajo.getText());
        num3 = num1 - num2;
        pantalla_abajo.setText(num3 + " ");
    }//GEN-LAST:event_btn_mas_menosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        igual = true;
        inicio = true;
        //condicion para la variable ejercicio1
        if (ejercicio1 = true) {
            valor1 = Double.parseDouble(pantalla_abajo.getText());
            double backupValue = (double)valor1;
            pantalla_arriba.setText(backupValue + " " + "MOD" + " ");
            ejercicio2 = false;
        } else {
            pantalla_arriba.setText(pantalla_arriba.getText()+ "MOD");
            operaciones(resultado, valor2);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_C;
    private javax.swing.JButton btn_CE;
    private javax.swing.JButton btn_MC;
    private javax.swing.JButton btn_MR;
    private javax.swing.JButton btn_MS;
    private javax.swing.JButton btn_M_mas;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_division;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_mas_menos;
    private javax.swing.JButton btn_mutiplica;
    private javax.swing.JButton btn_porciento;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mtn_M_menos;
    private javax.swing.JTextField pantalla_abajo;
    private javax.swing.JTextField pantalla_arriba;
    // End of variables declaration//GEN-END:variables
}
